Feat: Support Feed Service
GuGoOrg/GuGoTik pull request #27
Opened 2023-08-10 09:52 UTC by Attack825

feed service

2023-08-10 11:28 UTC, liaosunny123 commented
make func count unused temp to pass the lint ci

2023-08-10 11:36 UTC, liaosunny123 commented on src/constant/strings/feed.go
> +	VideoCount = 30
这个地方是什么意思？如果是const建议编码到对应的service里面

2023-08-10 11:52 UTC, liaosunny123 commented on src/services/feed/handler.go
> +	userErr := consul.RegisterConsul(config.UserRpcServerName, config.UserRpcServerPort)
此方法即将弃用，请关注Issue： #28

2023-08-10 11:57 UTC, liaosunny123 commented on src/services/feed/handler.go
> +	ctx, span := tracing.Tracer.Start(ctx, "ListVideosService")
Span中的OperationName和LogService的Name保持一致以方便查看

2023-08-10 11:58 UTC, liaosunny123 commented on src/services/feed/handler.go
> +	if request.LatestTime == nil {
相同的处理逻辑，去掉一个

2023-08-10 11:58 UTC, liaosunny123 commented on src/services/feed/handler.go
> +		//logging.SetSpanError(span, err)
需要SetSpanError以表示链路出现Error

2023-08-10 12:00 UTC, liaosunny123 commented on test/rpc/feedrpc_test.go
> +	assert.Equal(t, int32(0), res.StatusCode)
int32不需要显式添加类型转换

2023-08-10 12:03 UTC, liaosunny123 commented on src/web/feed/headler.go
> +	conn, err := grpc.Dial(
ditto

2023-08-10 12:04 UTC, liaosunny123 commented on src/services/feed/handler.go
> +				VideoId: uint32(v.ID),
显式ID的初始化，可以参考Issue： #18

2023-08-10 12:05 UTC, liaosunny123 commented on src/services/feed/handler.go
> +		Limit(strings.VideoCount).
ditto,硬编码到此文件,或者在Env做成可以配置的

2023-08-10 12:05 UTC, liaosunny123 commented on src/services/feed/handler.go
> +		StatusMsg:  ServiceOK,
没必要这样，都strings.ServiceOk

2023-08-10 12:07 UTC, liaosunny123 requested changes
参考对话解决掉出现的问题，同时如果是链接的Issue未PR可以等待PR后使用完善后的方法

2023-08-11 02:32 UTC, Attack825 commented on src/constant/strings/feed.go
> +	VideoCount = 30
收到

2023-08-11 02:42 UTC, Attack825 commented on src/services/feed/handler.go
> +	ctx, span := tracing.Tracer.Start(ctx, "ListVideosService")
我模仿的auth的logService:
https://github.com/GuGoOrg/GuGoTik/blob/e196a0c122b78e33fc5d970f009d324c568e09fa/src/services/auth/handler.go#L85C59-L87

2023-08-11 02:53 UTC, liaosunny123 commented on src/services/feed/handler.go
> +	ctx, span := tracing.Tracer.Start(ctx, "ListVideosService")
那就暂时这样，好像这个地方我以前专门改成这样了

2023-08-11 06:40 UTC, liaosunny123 approved these changes

2023-08-11 13:45 UTC, closed without merging