Relation
GuGoOrg/GuGoTik pull request #93
Opened 2023-08-20 01:36 UTC by amazing-compass

import cache

2023-08-20 15:29 UTC, liaosunny123 requested changes

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	}
重复代码逻辑

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	}
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		}
错误处理

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if cachedCountString, ok, _ := cached.Get(ctx, cacheKey); ok {
别把err吞了

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		logger.Infof("Cache hit for follow list count for user %d", request.UserId)
使用`logrus.Fields`和`log with field`来输出关键信息

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return resp, err
不需要，直接写return就行

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	countString := strconv.Itoa(int(count))
在32位的机器上这样操作是由问题的，通过uint来直接format

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if cachedCountString, ok, _ := cached.Get(ctx, cacheKey); ok {
err ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		}
err ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return resp, err
return ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	countString := strconv.Itoa(int(count))
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if ok, _ := cached.CacheAndRedisGet(ctx, cacheKey, &followList); ok {
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	}
return

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if ok, _ := cached.CacheAndRedisGet(ctx, cacheKey, &followerList); ok {
err

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		logger.Infof("Cache hit for follower list for user %d", request.UserId)
field format ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		}).Errorf("failed to write cache for follower list")
return

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	}
协程

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if ok, _ := cached.CacheAndRedisGet(ctx, cacheKey, &cachedFollowList); ok {
err ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +			return resp, err
return ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return resp, nil
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return resp, nil
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	return resp, nil
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		resp = &relation.FollowListResponse{
日志和SetSpanError

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		}).Errorf("failed to write cache for follow list")
return和日志输出

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if ok, _ := cached.CacheAndRedisGet(ctx, cacheKey, &cachedFollowerList); ok {
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +			return resp, err
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return resp, err
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return
链路，日志

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +					logging.SetSpanError(span, err)
在外面setSpanError，在这个地方就log就行，不然可能会出现重复SetSpanError

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		logger.Errorf("%d user information fails to be queried. ", len(wgErrors))
日志输出的格式

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		return nil, fmt.Errorf("%d user information fails to be queried", len(wgErrors))
return err

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +
链路没了

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	}
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +		}
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	cacheKey := fmt.Sprintf("follow_count_%d", actorID)
span

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if cachedCountString, ok, _ := cached.Get(ctx, cacheKey); ok {
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	if cachedCountString, ok, _ := cached.Get(ctx, cacheKey); ok {
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	countString := strconv.Itoa(int(count))
ditto

2023-08-20 15:29 UTC, liaosunny123 commented on src/services/relation/handler.go
> +	countString := strconv.Itoa(int(count))
ditto

2023-08-21 09:53 UTC, amazing-compass commented on src/services/relation/handler.go
> +	}
获取互关列表的，写缓存失败是无所谓的啊，大不了下次操作之后再读一次数据库，没必要因为这个就把这次操作直接return吧

2023-08-21 09:53 UTC, amazing-compass commented on src/services/relation/handler.go
> +		}).Errorf("failed to write cache for follower list")
ditto

2023-08-21 09:57 UTC, amazing-compass commented on src/services/relation/handler.go
> +		}).Errorf("failed to write cache for follow list")
ditto

2023-08-21 13:39 UTC, merged